name: Build & Deploy Spring App

#when to trigger the actions

on:
  push:
    branches:
      - main

jobs:
  #name to job
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Package and Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml